version: '2.4'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc -w 2 127.0.0.1 2181 | grep -q imok"]
      interval: 5s
      timeout: 10s
      retries: 15
      start_period: 10s

  kafka1:
    hostname: kafka1
    image: wurstmeister/kafka:2.12-2.3.1
    ports:
      - "9093:9093"
    volumes:
      - ./ssl:/ssl
      - ./scripts/kafka_check_health:/kafka_check_health
    env_file: docker-compose-kafka.env
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka1:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENERS: INSIDE://kafka1:9092,OUTSIDE://kafka1:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:SSL
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    healthcheck:
      test: /kafka_check_health
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 10s
    depends_on:
      zookeeper:
        condition: service_healthy

  kafka2:
    hostname: kafka2
    image: wurstmeister/kafka:2.12-2.3.1
    ports:
      - "9094:9094"
    volumes:
      - ./ssl:/ssl
      - ./scripts/kafka_check_health:/kafka_check_health
    env_file: docker-compose-kafka.env
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: kafka2
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka2:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENERS: INSIDE://kafka2:9092,OUTSIDE://kafka2:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:SSL
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    healthcheck:
      test: /kafka_check_health
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 10s
    depends_on:
      zookeeper:
        condition: service_healthy

  kafka3:
    hostname: kafka3
    image: wurstmeister/kafka:2.12-2.3.1
    ports:
      - "9095:9095"
    volumes:
      - ./ssl:/ssl
      - ./scripts/kafka_check_health:/kafka_check_health
    env_file: docker-compose-kafka.env
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_HOST_NAME: kafka3
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka3:9092,OUTSIDE://localhost:9095
      KAFKA_LISTENERS: INSIDE://kafka3:9092,OUTSIDE://kafka3:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:SSL
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    healthcheck:
      test: /kafka_check_health
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 10s
    depends_on:
      zookeeper:
        condition: service_healthy

  # This is a dummy service that forces all other services to be healthy before
  # docker-compose up can be considered successful.
  ready:
    image: busybox:1.31-musl
    command: tail -f /dev/null
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
